version: '3.8'

services:

  user-service:
    build: ./services/user-service
    ports:
      - "8080:8080"

  product-service:
    build: ./services/product-service
    ports:
      - "8082:8082"

  order-service:
    build: ./services/order-service
    ports:
      - "8083:8083"
