apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-config
data:
  USER_DB_URL: jdbc:postgresql://user-db:5432/users_db
  PRODUCT_DB_URL: jdbc:postgresql://product-db:5432/product_db

  USER_SERVICE_URL: http://user-service:8080
  PRODUCT_SERVICE_URL: http://product-service:8082
