apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secret
type: Opaque
stringData:
  USER_DB_USERNAME: user
  USER_DB_PASSWORD: password

  PRODUCT_DB_USERNAME: postgres
  PRODUCT_DB_PASSWORD: postgres
