spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://user-db:5432/users_db
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{X-Correlation-ID}] %-5level %logger - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info

  endpoint:
    health:
      show-details: always